spring:
  main:
    lazy-initialization: true
  application:
    name: notification-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/notification
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${POSTGRES_DEFAULT_SCHEMA:public}
        format_sql: true
        jdbc.time_zone: Asia/Seoul
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: notification-service-group
      topics:
        delivery-summary-generated: ai.delivery.info.generated

slack:
  token: ${SLACK_USER_TOKEN}
  baseUrl: ${SLACK_BASE_URL:https://slack.com/api}
  conversationOpenUrl: ${SLACK_CONVERSATION_OPEN_URL:/conversations.open}
  chatPostMessageUrl: ${SLACK_CHAT_POST_MESSAGE_URL:/chat.postMessage}
  webhook:
    url: ${SLACK_WEBHOOK_URL:${SLACK_BASE_URL:https://slack.com/api}}

server:
  port: ${NOTIFICATION_SERVER_PORT:8100}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true