spring:
  application:
    name: notification-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://notification-postgres:5100/notification}
    username: ${POSTGRES_USER:notification_admin}
    password: ${POSTGRES_PASSWORD:p@ssw0rd}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${POSTGRES_DEFAULT_SCHEMA:public}
        format_sql: true
        jdbc.time_zone: Asia/Seoul

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true