spring:
  application:
    name: hub-service

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key-spec: ${JWT_SECRET}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
    cache:
      type: redis

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://hub-db:5432/hub}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.cache: TRACE
    org.hibernate.orm.jdbc.bind: trace

kakao:
  api:
    key: ${KAKAO_API_KEY}

server:
  port: ${SERVER_PORT:8084}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}