server:
  port: ${SERVER_PORT}

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-auth-route
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: product-route
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: hub-route
          uri: lb://hub-service
          predicates:
            - Path=/api/hubs/**
        - id: company-route
          uri: lb://company-service
          predicates:
            - Path=/api/companies/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET}