server:
  port: ${SERVER_PORT}

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-auth-route
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: user-route-root
          uri: lb://user-service
          predicates:
            - Path=/api/users
        - id: user-route-sub
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: user-internal-route-root
          uri: lb://user-service
          predicates:
            - Path=/api/internal/users
        - id: user-internal-route-sub
          uri: lb://user-service
          predicates:
            - Path=/api/internal/users/**
        - id: product-route
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: hub-route
          uri: lb://hub-service
          predicates:
              - Path=/api/internal/hubs/**
        - id: hubpath-route
          uri: lb://hubpath-service
          predicates:
              - Path=/api/internal/hub-paths/**
        - id: company-route
          uri: lb://company-service
          predicates:
            - Path=/api/companies/**
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: delivery-route-root
          uri: lb://delivery-service
          predicates:
            - Path=/api/deliveries
        - id: delivery-route-sub
          uri: lb://delivery-service
          predicates:
            - Path=/api/deliveries/**
        - id: delivery-record-route
          uri: lb://delivery-service
          predicates:
            - Path=/api/delivery-routes/**
        - id: delivery-manager-route-root
          uri: lb://delivery-service
          predicates:
            - Path=/api/delivery-managers
        - id: delivery-manager-route-sub
          uri: lb://delivery-service
          predicates:
            - Path=/api/delivery-managers/**
        - id: user-service-docs
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/(?<segment>.*), /${segment}

        - id: company-service-docs
          uri: lb://company-service
          predicates:
            - Path=/company-service/v3/api-docs
          filters:
            - RewritePath=/company-service/(?<segment>.*), /${segment}

        - id: delivery-service-docs
          uri: lb://delivery-service
          predicates:
            - Path=/delivery-service/v3/api-docs
          filters:
            - RewritePath=/delivery-service/(?<segment>.*), /${segment}

        - id: hub-service-docs
          uri: lb://hub-service
          predicates:
            - Path=/hub-service/v3/api-docs
          filters:
            - RewritePath=/hub-service/(?<segment>.*), /${segment}

        - id: hubpath-service-docs
          uri: lb://hubpath-service
          predicates:
            - Path=/hubpath-service/v3/api-docs
          filters:
            - RewritePath=/hubpath-service/(?<segment>.*), /${segment}

        - id: product-service-docs
          uri: lb://product-service
          predicates:
            - Path=/product-service/v3/api-docs
          filters:
            - RewritePath=/product-service/(?<segment>.*), /${segment}

        - id: order-service-docs
          uri: lb://order-service
          predicates:
            - Path=/order-service/v3/api-docs
          filters:
            - RewritePath=/order-service/(?<segment>.*), /${segment}

        - id: notification-service-docs
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/v3/api-docs
          filters:
            - RewritePath=/notification-service/(?<segment>.*), /${segment}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: company-service
        url: /company-service/v3/api-docs
      - name: delivery-service
        url: /delivery-service/v3/api-docs
      - name: hub-service
        url: /hub-service/v3/api-docs
      - name: hubpath-service
        url: /hubpath-service/v3/api-docs
      - name: product-service
        url: /product-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
      - name: notification-service
        url: /notification-service/v3/api-docs