spring:
  datasource:
    url: jdbc:postgresql://localhost:5102/ai
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:test-key}

weather:
  api-key: ${OPENWEATHERMAP_API_KEY}
  base-url: https://api.openweathermap.org/data/2.5

kafka:
  bootstrap-servers: localhost:9092

server:
  port: 8102
