services:
  company-db:
    image: postgres:latest
    container_name: company-db
    restart: always
    environment:
      POSTGRES_DB: company
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Seoul
    ports:
      - "5433:5432"
    volumes:
      - company_db_data:/var/lib/postgresql/18/data
    networks:
      - company-network

networks:
  company-network:
    driver: bridge

volumes:
  company_db_data:
