server:
  port: ${SERVER_PORT}

spring:
  main:
    lazy-initialization: true
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info