spring:
  datasource:
    url: jdbc:postgresql://localhost:5094/delivery
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false