spring:
  datasource:
    url: jdbc:postgresql://delivery-db:5094/delivery
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
